"""
Renders the Terraform diff for a tag_remediation capability call.

This produces the content of the new .tf file that becomes the PR — it does
not run `terraform` itself. Reading current tags and resolving the project ID
(for GCP) is done by the capability agent via the MCP tool servers before
calling this function; render never resolves or guesses anything itself.
"""

from __future__ import annotations

from contracts.capability_contract import Cloud, TagComplianceRequest, TagRef


def tag_remediation_slug(request: TagComplianceRequest) -> str:
    return f"tags-{request.resource_id}".replace(".", "-").replace("_", "-").lower()


def _tags_block(tags: list[TagRef]) -> str:
    lines = "\n".join(f'    "{tag.key}" = "{tag.value}"' for tag in tags)
    return "{\n" + lines + "\n  }"


def render_tag_remediation_diff(
    request: TagComplianceRequest,
    proposed_tags: list[TagRef],
    *,
    project_id: str | None = None,
) -> str:
    slug = tag_remediation_slug(request)

    header = (
        f"# Auto-generated by Aegis tag_remediation capability agent — do not hand-edit\n"
        f"# resource_id   : {request.resource_id}\n"
        f"# requester     : {request.requester}\n"
        f"# justification : {request.justification}\n\n"
    )

    if request.cloud == Cloud.GCP:
        assert project_id, "GCP tag remediation diffs require a resolved project_id"
        body = (
            f'module "{slug}" {{\n'
            f'  source      = "../../modules/gcp/tagged_bucket"\n'
            f'  bucket_name = "{request.resource_id}"\n'
            f'  project     = "{project_id}"\n'
            f"  labels      = {_tags_block(proposed_tags)}\n"
            f"}}\n"
        )
    elif request.cloud == Cloud.AZURE:
        body = (
            f'module "{slug}" {{\n'
            f'  source               = "../../modules/azure/resource_tags"\n'
            f'  resource_group_name  = "{request.resource_id}"\n'
            f"  tags                 = {_tags_block(proposed_tags)}\n"
            f"}}\n"
        )
    else:
        raise ValueError(f"unsupported cloud: {request.cloud!r}")

    return header + body
