"""
Renders the Terraform diff for an approved access_grant capability call.

This produces the content of the new .tf file that becomes the PR — it does
not run `terraform` itself. The identity/project resolution the diff needs
(Entra object ID, GCP project ID) is done by the capability agent via the
MCP tool servers before calling this function; render never resolves or
guesses anything itself.
"""

from __future__ import annotations

from contracts.capability_contract import AccessGrantRequest
from contracts.entitlement_catalog import EntitlementCatalogEntry


def render_access_grant_diff(
    request: AccessGrantRequest,
    entry: EntitlementCatalogEntry,
    *,
    member_object_id: str | None = None,
    project_id: str | None = None,
) -> str:
    slug = f"{entry.id}-{request.requester.split('@')[0]}".replace(".", "-").replace("_", "-")

    header = (
        f"# Auto-generated by Aegis access_grant capability agent — do not hand-edit\n"
        f"# catalog_entry : {entry.id}\n"
        f"# requester     : {request.requester}\n"
        f"# justification : {request.justification}\n"
        f"# ttl_hours     : {request.ttl_hours} "
        f"(informational — expiry enforcement is out of MVP scope)\n\n"
    )

    if entry.resource_type == "entra_group":
        assert member_object_id, "entra_group diffs require a resolved member_object_id"
        body = (
            f'module "{slug}" {{\n'
            f'  source           = "../../{entry.terraform_module}"\n'
            f'  group_object_id  = "{entry.resource_id}"\n'
            f'  member_object_id = "{member_object_id}"\n'
            f"}}\n"
        )
    elif entry.resource_type == "iam_binding":
        assert project_id, "iam_binding diffs require a resolved project_id"
        body = (
            f'module "{slug}" {{\n'
            f'  source  = "../../{entry.terraform_module}"\n'
            f'  role    = "{entry.resource_id}"\n'
            f'  member  = "user:{request.requester}"\n'
            f'  project = "{project_id}"\n'
            f"}}\n"
        )
    else:
        raise ValueError(f"unsupported resource_type: {entry.resource_type!r}")

    return header + body
