# Auto-generated by Aegis tag_remediation capability agent — do not hand-edit
# resource_id   : aegis-demo-tag-final-fix-verify
# requester     : jane.doe@example.com
# justification : Final verification after fixing the GCP label sanitization bug

module "tags-aegis-demo-tag-final-fix-verify" {
  source      = "../../modules/gcp/tagged_bucket"
  bucket_name = "aegis-demo-tag-final-fix-verify"
  project     = "ual-demo-af168"
  labels      = {
    "cost-center" = "pmt-01"
    "environment" = "nonprod"
    "owner" = "jane-doe-example-com"
  }
}
