# Auto-generated by Aegis tag_remediation capability agent — do not hand-edit
# resource_id   : aegis-demo-tag-ci-verify-4
# requester     : jane.doe@example.com
# justification : Final CI verification for real terraform apply of tag remediation

module "tags-aegis-demo-tag-ci-verify-4" {
  source      = "../../modules/gcp/tagged_bucket"
  bucket_name = "aegis-demo-tag-ci-verify-4"
  project     = "ual-demo-af168"
  labels      = {
    "cost-center" = "PMT-01"
    "environment" = "nonprod"
    "owner" = "jane.doe@example.com"
  }
}
