# Generated by Aegis Governed Delivery. Do not edit manually.
# action_request_id: 5d403b49-cbfb-4f11-8935-d2830f6fbeba
# expires_after_hours: 1

module "aegis_request_5d403b49_cbfb_4f11_8935_d2830f6fbeba" {
  source  = "../../modules/gcp/iam_binding"
  project = "ual-demo-af168"
  role    = "roles/viewer"
  member  = "user:aegis-p0-requester-5e3c44084de2@example.com"
}
