# Generated by Aegis Governed Delivery. Do not edit manually.
# action_request_id: 5dc5c985-29b2-4805-b73c-62fb06218126
# expires_after_hours: 1

module "aegis_request_5dc5c985_29b2_4805_b73c_62fb06218126" {
  source  = "../../modules/gcp/iam_binding"
  project = "ual-demo-af168"
  role    = "roles/viewer"
  member  = "user:aegis-p0-requester-be6181de8321@example.com"
}
