# Auto-generated by Aegis access_grant capability agent — do not hand-edit
# catalog_entry : azure-payments-nonprod-tier2
# requester     : jane.doe@example.com
# justification : Give me temporary Tier-2 access to payments non-prod for 8 hours, debugging a reconciliation issue
# ttl_hours     : 8 (informational — expiry enforcement is out of MVP scope)

module "azure-payments-nonprod-tier2-jane-doe" {
  source           = "../../modules/azure/entra_group_membership"
  group_object_id  = "00000000-0000-0000-0000-000000000101"
  member_object_id = "11111111-1111-1111-1111-111111111111"
}
