# Auto-generated by Aegis access_grant capability agent — do not hand-edit
# catalog_entry : gcp-payments-nonprod-tier2
# requester     : jane.doe@example.com
# justification : Give me temporary Tier-2 access to payments non-prod for 8 hours, debugging a reconciliation issue
# ttl_hours     : 8 (informational — expiry enforcement is out of MVP scope)

module "gcp-payments-nonprod-tier2-jane-doe" {
  source  = "../../modules/gcp/iam_binding"
  role    = "roles/editor"
  member  = "user:jane.doe@example.com"
  project = "ual-demo-af168"
}
