# Auto-generated by Aegis access_grant capability agent — do not hand-edit
# catalog_entry : gcp-payments-nonprod-tier2
# requester     : apatil0431@gmail.com
# justification : this temp access to create. continer
# ttl_hours     : 8 (informational — expiry enforcement is out of MVP scope)

module "gcp-payments-nonprod-tier2-apatil0431" {
  source  = "../../modules/gcp/iam_binding"
  role    = "roles/editor"
  member  = "user:apatil0431@gmail.com"
  project = "ual-demo-af168"
}
