# Auto-generated by Aegis access_grant capability agent — do not hand-edit
# catalog_entry : gcp-payments-nonprod-tier2
# requester     : happyanand06@gmail.com
# justification : project work
# ttl_hours     : 8 (informational — expiry enforcement is out of MVP scope)

module "gcp-payments-nonprod-tier2-happyanand06" {
  source  = "../../modules/gcp/iam_binding"
  role    = "roles/editor"
  member  = "user:happyanand06@gmail.com"
  project = "ual-demo-af168"
}
