# Auto-generated by Aegis access_grant capability agent — do not hand-edit
# catalog_entry : gcp-payments-nonprod-tier1
# requester     : bhappyadi@gmail.com
# justification : Give me temporary Tier-1 read-only access to payments non-prod for 24 hours to review configs
# ttl_hours     : 24 (informational — expiry enforcement is out of MVP scope)

module "gcp-payments-nonprod-tier1-bhappyadi" {
  source  = "../../modules/gcp/iam_binding"
  role    = "roles/viewer"
  member  = "user:bhappyadi@gmail.com"
  project = "ual-demo-af168"
}
