# Auto-generated by Aegis access_grant capability agent — do not hand-edit
# catalog_entry : gcp-payments-nonprod-tier2
# requester     : bhappyadi@gmail.com
# justification : Final complete end-to-end test: submit, approve, PR, merge, apply
# ttl_hours     : 8 (informational — expiry enforcement is out of MVP scope)

module "gcp-payments-nonprod-tier2-bhappyadi" {
  source  = "../../modules/gcp/iam_binding"
  role    = "roles/editor"
  member  = "user:bhappyadi@gmail.com"
  project = "ual-demo-af168"
}
